//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Transaction_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acc_Transaction_MST()
        {
            this.Acc_Transaction_DTL = new HashSet<Acc_Transaction_DTL>();
        }
    
        public int ID { get; set; }
        public long Serial { get; set; }
        public Nullable<int> Rec_Code { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> Type_Code { get; set; }
        public string RecDate_G { get; set; }
        public Nullable<int> C_RecDate_G { get; set; }
        public Nullable<int> ProcType { get; set; }
        public Nullable<int> Cash_Bnk_No { get; set; }
        public string Acc_Code { get; set; }
        public string Cur_Code { get; set; }
        public Nullable<float> Cur_Rate { get; set; }
        public Nullable<float> Amount { get; set; }
        public Nullable<float> FAmount { get; set; }
        public string T_Desc { get; set; }
        public Nullable<long> Ref { get; set; }
        public Nullable<int> WorthType { get; set; }
        public Nullable<int> Collector_Code { get; set; }
        public Nullable<int> w_Code { get; set; }
        public Nullable<int> CC_Code { get; set; }
        public Nullable<int> Proj_Code { get; set; }
        public string Tagged { get; set; }
        public Nullable<int> Mnth { get; set; }
        public Nullable<int> year { get; set; }
        public string Machine_Nm { get; set; }
        public Nullable<int> Brn_No { get; set; }
        public string adUser { get; set; }
        public string adDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
        public Nullable<int> EditCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc_Transaction_DTL> Acc_Transaction_DTL { get; set; }
    }
}
