//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_CashBnk_Currency
    {
        public int ID { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> Cash_Bnk_No { get; set; }
        public string Cur_Code { get; set; }
        public Nullable<bool> used { get; set; }
    }
}
