//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_CostCenter_Projects
    {
        public int ID { get; set; }
        public Nullable<int> DocType { get; set; }
        public string CC_Code { get; set; }
        public string CC_Parent { get; set; }
        public string NmAr { get; set; }
        public string NmEn { get; set; }
        public Nullable<int> CC_Type { get; set; }
        public int CC_Level { get; set; }
        public Nullable<int> CC_Group { get; set; }
        public bool State { get; set; }
        public string Note { get; set; }
        public string adUser { get; set; }
        public string adDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
