//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Cash_AtBank
    {
        public int Bnk_No { get; set; }
        public string NmAr { get; set; }
        public string NmEn { get; set; }
        public string Acc_Code { get; set; }
        public string Acc_InBank { get; set; }
        public string IBAN { get; set; }
        public Nullable<int> Seq { get; set; }
        public string adrs { get; set; }
        public string WebSite { get; set; }
        public string Phons { get; set; }
        public Nullable<int> BRN_No { get; set; }
        public string Note { get; set; }
        public Nullable<bool> state { get; set; }
        public string adUser { get; set; }
        public string adDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
