//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_AccountLinked
    {
        public int ID { get; set; }
        public string StorOrMainGroup_Code { get; set; }
        public string Stor_Acc { get; set; }
        public string Sales_Acc { get; set; }
        public string SalesGroupCost_Acc { get; set; }
        public string SalesCostFreeQnty_Acc { get; set; }
        public string ReturnedOnSales_Acc { get; set; }
        public string ReturnedOnCostSales_Acc { get; set; }
        public string ReturnedOnSalesLastYears_Acc { get; set; }
        public string ReturnedCostOnSalesLastYears_Acc { get; set; }
        public string ReturnedOnSalesFreeQntyLastYears_Acc { get; set; }
        public string AllowableDiscount_Acc { get; set; }
        public string EarnedDiscount_Acc { get; set; }
        public string PurchaseCostFreeQnty_Acc { get; set; }
        public string Cost_differences_account { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
