//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_AccountLinkeds
    {
        public int ID { get; set; }
        public string StorOrMainGroup_Code { get; set; }
        public string Stor_Acc { get; set; }
        public string SalesCost_Acc { get; set; }
        public string Sales_Acc { get; set; }
        public string PurchCost_Acc { get; set; }
        public string SalesCostFreeQnty_Acc { get; set; }
        public string ReturnedOnSales_Acc { get; set; }
        public string ReturnedOnSalesFreeQnty_Acc { get; set; }
        public string ReturnedOnCostSales_Acc { get; set; }
        public string SalesDiscount_1_Acc { get; set; }
        public string SalesDiscount_2_Acc { get; set; }
        public string SalesDiscount_3_Acc { get; set; }
        public string SalesExtraDiscount_Acc { get; set; }
        public string PurchCostFreeQnty_Acc { get; set; }
        public string PurchDiscount_1_Acc { get; set; }
        public string PurchDiscount_2_Acc { get; set; }
        public string PurchDiscount_3_Acc { get; set; }
        public string PurchExtraDiscount_Acc { get; set; }
        public string EarnedDiscount_Acc { get; set; }
        public string TaxPayable_Acc { get; set; }
        public string TaxPaid_Acc { get; set; }
        public string Cost_differences_account { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
