//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Item_Units
    {
        public decimal ID { get; set; }
        public long Code { get; set; }
        public string Itm_Code { get; set; }
        public string Unt_Code { get; set; }
        public Nullable<int> Unt_Size { get; set; }
        public Nullable<decimal> Wght_In_KG { get; set; }
        public string Barcode_No { get; set; }
        public Nullable<decimal> Low_Lmt { get; set; }
        public Nullable<decimal> Upp_Lmt { get; set; }
        public Nullable<bool> isDeflt { get; set; }
        public Nullable<bool> isDeflt_Sal { get; set; }
        public Nullable<bool> isDeflt_Pur { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
