//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Itm_Mov
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string Trns_Type { get; set; }
        public string Trns_CodeNo { get; set; }
        public string Trns_Serial { get; set; }
        public string Itm_Code { get; set; }
        public string Stor_Code { get; set; }
        public string Unt_Code { get; set; }
        public Nullable<int> Qnty_In { get; set; }
        public Nullable<int> Qnty_Out { get; set; }
        public Nullable<decimal> AVG_Cost { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public Nullable<int> State { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
