//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Trans_Out_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inv_Trans_Out_MST()
        {
            this.Inv_Trans_Out_DTL = new HashSet<Inv_Trans_Out_DTL>();
        }
    
        public int ID { get; set; }
        public long Serial { get; set; }
        public long Bill_Code { get; set; }
        public string BRN_Code { get; set; }
        public Nullable<int> ProcType { get; set; }
        public string Process_Date { get; set; }
        public Nullable<int> C_Date { get; set; }
        public Nullable<int> C_Time { get; set; }
        public string WorthDate { get; set; }
        public string CG_Acc { get; set; }
        public string SubType { get; set; }
        public string Cash_Bnk_S_Code { get; set; }
        public string Cur_Code { get; set; }
        public Nullable<float> Cur_Rate { get; set; }
        public Nullable<float> w_Rate { get; set; }
        public Nullable<int> CostMethod { get; set; }
        public string Stor_Code { get; set; }
        public string CC_Code { get; set; }
        public string Proj_Code { get; set; }
        public Nullable<float> Bill_Total { get; set; }
        public string description { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
        public Nullable<int> Item_Count { get; set; }
        public Nullable<int> EditCount { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public Nullable<int> PiecesCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inv_Trans_Out_DTL> Inv_Trans_Out_DTL { get; set; }
        public virtual Inv_Trans_Out_MST Inv_Trans_Out_MST1 { get; set; }
        public virtual Inv_Trans_Out_MST Inv_Trans_Out_MST2 { get; set; }
    }
}
