//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AccSys_JZ20171Entities1 : DbContext
    {
        public AccSys_JZ20171Entities1()
            : base("name=AccSys_JZ20171Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Acc_Setting> C_Acc_Setting { get; set; }
        public virtual DbSet<C_Genral_Setting> C_Genral_Setting { get; set; }
        public virtual DbSet<C_Inv_Setting> C_Inv_Setting { get; set; }
        public virtual DbSet<C_Purch_Setting> C_Purch_Setting { get; set; }
        public virtual DbSet<C_Sales_Setting> C_Sales_Setting { get; set; }
        public virtual DbSet<Acc_AccountLinked> Acc_AccountLinked { get; set; }
        public virtual DbSet<Acc_Accounts> Acc_Accounts { get; set; }
        public virtual DbSet<Acc_Cash_AtBank> Acc_Cash_AtBank { get; set; }
        public virtual DbSet<Acc_Cash_InHand> Acc_Cash_InHand { get; set; }
        public virtual DbSet<Acc_CashBnk_Currency> Acc_CashBnk_Currency { get; set; }
        public virtual DbSet<Acc_Collectors> Acc_Collectors { get; set; }
        public virtual DbSet<Acc_CostCenter_Projects> Acc_CostCenter_Projects { get; set; }
        public virtual DbSet<Acc_Currency> Acc_Currency { get; set; }
        public virtual DbSet<Acc_OpenBalance> Acc_OpenBalance { get; set; }
        public virtual DbSet<Acc_Transaction_DTL> Acc_Transaction_DTL { get; set; }
        public virtual DbSet<Acc_Transaction_MST> Acc_Transaction_MST { get; set; }
        public virtual DbSet<Acc_VisaTypes> Acc_VisaTypes { get; set; }
        public virtual DbSet<Acc_VisaTypes_Comm> Acc_VisaTypes_Comm { get; set; }
        public virtual DbSet<Inv_AccountLinked> Inv_AccountLinked { get; set; }
        public virtual DbSet<Inv_AccountLinkeds> Inv_AccountLinkeds { get; set; }
        public virtual DbSet<Inv_Favorite_Groups> Inv_Favorite_Groups { get; set; }
        public virtual DbSet<Inv_Item_Barcode> Inv_Item_Barcode { get; set; }
        public virtual DbSet<Inv_Item_Types> Inv_Item_Types { get; set; }
        public virtual DbSet<Inv_Item_Units> Inv_Item_Units { get; set; }
        public virtual DbSet<Inv_Items> Inv_Items { get; set; }
        public virtual DbSet<Inv_Items_Classification> Inv_Items_Classification { get; set; }
        public virtual DbSet<Inv_Items_Pricing> Inv_Items_Pricing { get; set; }
        public virtual DbSet<Inv_Items_Suppliers> Inv_Items_Suppliers { get; set; }
        public virtual DbSet<Inv_Itm_Mov> Inv_Itm_Mov { get; set; }
        public virtual DbSet<Inv_Itm_Mov2> Inv_Itm_Mov2 { get; set; }
        public virtual DbSet<Inv_Main_Groups> Inv_Main_Groups { get; set; }
        public virtual DbSet<Inv_OpeningBalance> Inv_OpeningBalance { get; set; }
        public virtual DbSet<Inv_Pricing_Levels> Inv_Pricing_Levels { get; set; }
        public virtual DbSet<Inv_Receiving_DTL> Inv_Receiving_DTL { get; set; }
        public virtual DbSet<Inv_Receiving_MST> Inv_Receiving_MST { get; set; }
        public virtual DbSet<Inv_Store_Places> Inv_Store_Places { get; set; }
        public virtual DbSet<Inv_Stores> Inv_Stores { get; set; }
        public virtual DbSet<Inv_Storing> Inv_Storing { get; set; }
        public virtual DbSet<Inv_Trans_In_DTL> Inv_Trans_In_DTL { get; set; }
        public virtual DbSet<Inv_Trans_In_MST> Inv_Trans_In_MST { get; set; }
        public virtual DbSet<Inv_Trans_Out_DTL> Inv_Trans_Out_DTL { get; set; }
        public virtual DbSet<Inv_Trans_Out_MST> Inv_Trans_Out_MST { get; set; }
        public virtual DbSet<Inv_Transfer_DTL> Inv_Transfer_DTL { get; set; }
        public virtual DbSet<Inv_Transfer_MST> Inv_Transfer_MST { get; set; }
        public virtual DbSet<Inv_Transfer_Receiving_Types> Inv_Transfer_Receiving_Types { get; set; }
        public virtual DbSet<Inv_Trns_Types> Inv_Trns_Types { get; set; }
        public virtual DbSet<Inv_Units> Inv_Units { get; set; }
        public virtual DbSet<Purch_Burdens> Purch_Burdens { get; set; }
        public virtual DbSet<Purch_Invoice_Burdens> Purch_Invoice_Burdens { get; set; }
        public virtual DbSet<Purch_Invoice_DTL> Purch_Invoice_DTL { get; set; }
        public virtual DbSet<Purch_Invoice_Expenses> Purch_Invoice_Expenses { get; set; }
        public virtual DbSet<Purch_Invoice_Installment> Purch_Invoice_Installment { get; set; }
        public virtual DbSet<Purch_Invoice_MST> Purch_Invoice_MST { get; set; }
        public virtual DbSet<Purch_Refund_Invoice_DTL> Purch_Refund_Invoice_DTL { get; set; }
        public virtual DbSet<Purch_Refund_Invoice_MST> Purch_Refund_Invoice_MST { get; set; }
        public virtual DbSet<Purch_Suppler_Cur> Purch_Suppler_Cur { get; set; }
        public virtual DbSet<Purch_SupplerGroups> Purch_SupplerGroups { get; set; }
        public virtual DbSet<Purch_Supplers> Purch_Supplers { get; set; }
        public virtual DbSet<Sales_Customer_Cur> Sales_Customer_Cur { get; set; }
        public virtual DbSet<Sales_CustomerGroups> Sales_CustomerGroups { get; set; }
        public virtual DbSet<Sales_Customers> Sales_Customers { get; set; }
        public virtual DbSet<Sales_Invoice_DTL> Sales_Invoice_DTL { get; set; }
        public virtual DbSet<Sales_Invoice_Mst> Sales_Invoice_Mst { get; set; }
        public virtual DbSet<Sales_Refund_Invoice_DTL> Sales_Refund_Invoice_DTL { get; set; }
        public virtual DbSet<Sales_Refund_Invoice_MST> Sales_Refund_Invoice_MST { get; set; }
        public virtual DbSet<Sys_Areas> Sys_Areas { get; set; }
        public virtual DbSet<Sys_BRN> Sys_BRN { get; set; }
        public virtual DbSet<Sys_CMP> Sys_CMP { get; set; }
        public virtual DbSet<Sys_CodeList> Sys_CodeList { get; set; }
        public virtual DbSet<Sys_ExecptionAchive> Sys_ExecptionAchive { get; set; }
        public virtual DbSet<Sys_FiscalMonths> Sys_FiscalMonths { get; set; }
        public virtual DbSet<Sys_FiscalYears> Sys_FiscalYears { get; set; }
        public virtual DbSet<Sys_Lists> Sys_Lists { get; set; }
        public virtual DbSet<Sys_Machines> Sys_Machines { get; set; }
        public virtual DbSet<Sys_Perm_Definition> Sys_Perm_Definition { get; set; }
        public virtual DbSet<Sys_Rep_Tmplts> Sys_Rep_Tmplts { get; set; }
        public virtual DbSet<Sys_Rep_Types> Sys_Rep_Types { get; set; }
        public virtual DbSet<Sys_ReportHeaderFoter2> Sys_ReportHeaderFoter2 { get; set; }
        public virtual DbSet<sys_SystemTree> sys_SystemTree { get; set; }
        public virtual DbSet<Sys_Trans_Types> Sys_Trans_Types { get; set; }
        public virtual DbSet<Sys_UserLog> Sys_UserLog { get; set; }
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
        public virtual DbSet<Inv_Trans_In_DTL_Deleted> Inv_Trans_In_DTL_Deleted { get; set; }
        public virtual DbSet<Inv_Trans_Out_DTL_Deleted> Inv_Trans_Out_DTL_Deleted { get; set; }
        public virtual DbSet<Purch_Invoice_DTL_Deleted> Purch_Invoice_DTL_Deleted { get; set; }
        public virtual DbSet<Purch_Refund_Invoice_DTL_Deleted> Purch_Refund_Invoice_DTL_Deleted { get; set; }
        public virtual DbSet<tst> tsts { get; set; }
        public virtual DbSet<View_2> View_2 { get; set; }
        public virtual DbSet<vw_FillItemsPricing> vw_FillItemsPricing { get; set; }
        public virtual DbSet<vw_FillOpeningBalance> vw_FillOpeningBalance { get; set; }
        public virtual DbSet<vw_Inv_ItemsLov> vw_Inv_ItemsLov { get; set; }
        public virtual DbSet<vw_Inv_ItmPricingBrowse> vw_Inv_ItmPricingBrowse { get; set; }
        public virtual DbSet<vw_Inv_OpenBalanceBrowse> vw_Inv_OpenBalanceBrowse { get; set; }
        public virtual DbSet<vw_ItmUntPricing> vw_ItmUntPricing { get; set; }
        public virtual DbSet<vw_Pur_Rep_Debt_Aging> vw_Pur_Rep_Debt_Aging { get; set; }
        public virtual DbSet<vw_rep_AccSheet> vw_rep_AccSheet { get; set; }
        public virtual DbSet<vw_rep_AccVouchers> vw_rep_AccVouchers { get; set; }
        public virtual DbSet<vw_rep_Audit_Balance> vw_rep_Audit_Balance { get; set; }
        public virtual DbSet<vw_rep_Audit_Balance1> vw_rep_Audit_Balance1 { get; set; }
        public virtual DbSet<vw_rep_Inv_ItmPricing> vw_rep_Inv_ItmPricing { get; set; }
        public virtual DbSet<vw_rep_Inv_OpeningBalance> vw_rep_Inv_OpeningBalance { get; set; }
        public virtual DbSet<vw_rep_Inv_Stor_Movment1> vw_rep_Inv_Stor_Movment1 { get; set; }
        public virtual DbSet<vw_rep_Inv_Storing_Movment> vw_rep_Inv_Storing_Movment { get; set; }
        public virtual DbSet<vw_rep_Inv_Storing_Movment_TurnOverSales> vw_rep_Inv_Storing_Movment_TurnOverSales { get; set; }
        public virtual DbSet<vw_rep_Inv_Storing_Movments> vw_rep_Inv_Storing_Movments { get; set; }
        public virtual DbSet<vw_rep_Inv_Storing1> vw_rep_Inv_Storing1 { get; set; }
        public virtual DbSet<vw_rep_Inv_TransferDTL> vw_rep_Inv_TransferDTL { get; set; }
        public virtual DbSet<vw_rep_Inv_TransferMST> vw_rep_Inv_TransferMST { get; set; }
        public virtual DbSet<vw_rep_ItemsData> vw_rep_ItemsData { get; set; }
        public virtual DbSet<vw_rep_PurInvoiceDTL> vw_rep_PurInvoiceDTL { get; set; }
        public virtual DbSet<vw_rep_PurInvoiceDTL_Sub> vw_rep_PurInvoiceDTL_Sub { get; set; }
        public virtual DbSet<vw_rep_PurInvoiceEXP> vw_rep_PurInvoiceEXP { get; set; }
        public virtual DbSet<vw_rep_PurInvoiceMST> vw_rep_PurInvoiceMST { get; set; }
        public virtual DbSet<vw_rep_PurNet_MST> vw_rep_PurNet_MST { get; set; }
        public virtual DbSet<vw_rep_RefundInvoiceDTL> vw_rep_RefundInvoiceDTL { get; set; }
        public virtual DbSet<vw_rep_RefundInvoiceMST> vw_rep_RefundInvoiceMST { get; set; }
        public virtual DbSet<vw_rep_Sal_Customers> vw_rep_Sal_Customers { get; set; }
        public virtual DbSet<vw_rep_Sal_Debt_Aging> vw_rep_Sal_Debt_Aging { get; set; }
        public virtual DbSet<vw_rep_Sal_InvoiceDTL> vw_rep_Sal_InvoiceDTL { get; set; }
        public virtual DbSet<vw_rep_Sal_InvoiceMST> vw_rep_Sal_InvoiceMST { get; set; }
        public virtual DbSet<vw_rep_Sal_ProfitMargin> vw_rep_Sal_ProfitMargin { get; set; }
        public virtual DbSet<vw_rep_Sal_RefundInvoiceDTL> vw_rep_Sal_RefundInvoiceDTL { get; set; }
        public virtual DbSet<vw_rep_Sal_RefundInvoiceMST> vw_rep_Sal_RefundInvoiceMST { get; set; }
        public virtual DbSet<vw_rep_SalNet_MST> vw_rep_SalNet_MST { get; set; }
        public virtual DbSet<vw_rep_SerialsWithProcCode> vw_rep_SerialsWithProcCode { get; set; }
        public virtual DbSet<vw_rep_Supplyer> vw_rep_Supplyer { get; set; }
        public virtual DbSet<vw_ReportHeaderFoter2> vw_ReportHeaderFoter2 { get; set; }
    
        public virtual int GetUnitPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetUnitPrice");
        }
    
        public virtual int NewDeleteCommand(string itm_Code, string unt_Code)
        {
            var itm_CodeParameter = itm_Code != null ?
                new ObjectParameter("Itm_Code", itm_Code) :
                new ObjectParameter("Itm_Code", typeof(string));
    
            var unt_CodeParameter = unt_Code != null ?
                new ObjectParameter("Unt_Code", unt_Code) :
                new ObjectParameter("Unt_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NewDeleteCommand", itm_CodeParameter, unt_CodeParameter);
        }
    
        public virtual int NewInsertCommand(Nullable<long> code, string itm_Code, string unt_Code, Nullable<int> itm_Pkg, Nullable<decimal> unt_Price, Nullable<decimal> wght_In_KG, string barcode_No, Nullable<decimal> low_Lmt, Nullable<decimal> upp_Lmt, Nullable<bool> isDeflt, Nullable<bool> isDeflt_Sal, Nullable<bool> isDeflt_Pur, string adUser, string adDate, string editUser, string editDate)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(long));
    
            var itm_CodeParameter = itm_Code != null ?
                new ObjectParameter("Itm_Code", itm_Code) :
                new ObjectParameter("Itm_Code", typeof(string));
    
            var unt_CodeParameter = unt_Code != null ?
                new ObjectParameter("Unt_Code", unt_Code) :
                new ObjectParameter("Unt_Code", typeof(string));
    
            var itm_PkgParameter = itm_Pkg.HasValue ?
                new ObjectParameter("Itm_Pkg", itm_Pkg) :
                new ObjectParameter("Itm_Pkg", typeof(int));
    
            var unt_PriceParameter = unt_Price.HasValue ?
                new ObjectParameter("Unt_Price", unt_Price) :
                new ObjectParameter("Unt_Price", typeof(decimal));
    
            var wght_In_KGParameter = wght_In_KG.HasValue ?
                new ObjectParameter("Wght_In_KG", wght_In_KG) :
                new ObjectParameter("Wght_In_KG", typeof(decimal));
    
            var barcode_NoParameter = barcode_No != null ?
                new ObjectParameter("Barcode_No", barcode_No) :
                new ObjectParameter("Barcode_No", typeof(string));
    
            var low_LmtParameter = low_Lmt.HasValue ?
                new ObjectParameter("Low_Lmt", low_Lmt) :
                new ObjectParameter("Low_Lmt", typeof(decimal));
    
            var upp_LmtParameter = upp_Lmt.HasValue ?
                new ObjectParameter("Upp_Lmt", upp_Lmt) :
                new ObjectParameter("Upp_Lmt", typeof(decimal));
    
            var isDefltParameter = isDeflt.HasValue ?
                new ObjectParameter("isDeflt", isDeflt) :
                new ObjectParameter("isDeflt", typeof(bool));
    
            var isDeflt_SalParameter = isDeflt_Sal.HasValue ?
                new ObjectParameter("isDeflt_Sal", isDeflt_Sal) :
                new ObjectParameter("isDeflt_Sal", typeof(bool));
    
            var isDeflt_PurParameter = isDeflt_Pur.HasValue ?
                new ObjectParameter("isDeflt_Pur", isDeflt_Pur) :
                new ObjectParameter("isDeflt_Pur", typeof(bool));
    
            var adUserParameter = adUser != null ?
                new ObjectParameter("AdUser", adUser) :
                new ObjectParameter("AdUser", typeof(string));
    
            var adDateParameter = adDate != null ?
                new ObjectParameter("AdDate", adDate) :
                new ObjectParameter("AdDate", typeof(string));
    
            var editUserParameter = editUser != null ?
                new ObjectParameter("EditUser", editUser) :
                new ObjectParameter("EditUser", typeof(string));
    
            var editDateParameter = editDate != null ?
                new ObjectParameter("EditDate", editDate) :
                new ObjectParameter("EditDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NewInsertCommand", codeParameter, itm_CodeParameter, unt_CodeParameter, itm_PkgParameter, unt_PriceParameter, wght_In_KGParameter, barcode_NoParameter, low_LmtParameter, upp_LmtParameter, isDefltParameter, isDeflt_SalParameter, isDeflt_PurParameter, adUserParameter, adDateParameter, editUserParameter, editDateParameter);
        }
    
        public virtual int NewSelectCommand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NewSelectCommand");
        }
    
        public virtual int NewUpdateCommand(Nullable<long> code, string itm_Code, string unt_Code, Nullable<int> itm_Pkg, Nullable<decimal> cost_Price, Nullable<decimal> wght_In_KG, string barcode_No, Nullable<decimal> low_Lmt, Nullable<decimal> upp_Lmt, Nullable<bool> isDeflt, Nullable<bool> isDeflt_Sal, Nullable<bool> isDeflt_Pur, string adUser, string adDate, string editUser, string editDate, Nullable<long> original_Code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(long));
    
            var itm_CodeParameter = itm_Code != null ?
                new ObjectParameter("Itm_Code", itm_Code) :
                new ObjectParameter("Itm_Code", typeof(string));
    
            var unt_CodeParameter = unt_Code != null ?
                new ObjectParameter("Unt_Code", unt_Code) :
                new ObjectParameter("Unt_Code", typeof(string));
    
            var itm_PkgParameter = itm_Pkg.HasValue ?
                new ObjectParameter("Itm_Pkg", itm_Pkg) :
                new ObjectParameter("Itm_Pkg", typeof(int));
    
            var cost_PriceParameter = cost_Price.HasValue ?
                new ObjectParameter("Cost_Price", cost_Price) :
                new ObjectParameter("Cost_Price", typeof(decimal));
    
            var wght_In_KGParameter = wght_In_KG.HasValue ?
                new ObjectParameter("Wght_In_KG", wght_In_KG) :
                new ObjectParameter("Wght_In_KG", typeof(decimal));
    
            var barcode_NoParameter = barcode_No != null ?
                new ObjectParameter("Barcode_No", barcode_No) :
                new ObjectParameter("Barcode_No", typeof(string));
    
            var low_LmtParameter = low_Lmt.HasValue ?
                new ObjectParameter("Low_Lmt", low_Lmt) :
                new ObjectParameter("Low_Lmt", typeof(decimal));
    
            var upp_LmtParameter = upp_Lmt.HasValue ?
                new ObjectParameter("Upp_Lmt", upp_Lmt) :
                new ObjectParameter("Upp_Lmt", typeof(decimal));
    
            var isDefltParameter = isDeflt.HasValue ?
                new ObjectParameter("isDeflt", isDeflt) :
                new ObjectParameter("isDeflt", typeof(bool));
    
            var isDeflt_SalParameter = isDeflt_Sal.HasValue ?
                new ObjectParameter("isDeflt_Sal", isDeflt_Sal) :
                new ObjectParameter("isDeflt_Sal", typeof(bool));
    
            var isDeflt_PurParameter = isDeflt_Pur.HasValue ?
                new ObjectParameter("isDeflt_Pur", isDeflt_Pur) :
                new ObjectParameter("isDeflt_Pur", typeof(bool));
    
            var adUserParameter = adUser != null ?
                new ObjectParameter("AdUser", adUser) :
                new ObjectParameter("AdUser", typeof(string));
    
            var adDateParameter = adDate != null ?
                new ObjectParameter("AdDate", adDate) :
                new ObjectParameter("AdDate", typeof(string));
    
            var editUserParameter = editUser != null ?
                new ObjectParameter("EditUser", editUser) :
                new ObjectParameter("EditUser", typeof(string));
    
            var editDateParameter = editDate != null ?
                new ObjectParameter("EditDate", editDate) :
                new ObjectParameter("EditDate", typeof(string));
    
            var original_CodeParameter = original_Code.HasValue ?
                new ObjectParameter("Original_Code", original_Code) :
                new ObjectParameter("Original_Code", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NewUpdateCommand", codeParameter, itm_CodeParameter, unt_CodeParameter, itm_PkgParameter, cost_PriceParameter, wght_In_KGParameter, barcode_NoParameter, low_LmtParameter, upp_LmtParameter, isDefltParameter, isDeflt_SalParameter, isDeflt_PurParameter, adUserParameter, adDateParameter, editUserParameter, editDateParameter, original_CodeParameter);
        }
    }
}
