//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purch_Invoice_Installment
    {
        public int ID { get; set; }
        public long Serial { get; set; }
        public long Bill_Code { get; set; }
        public string Installment_Code { get; set; }
        public Nullable<float> Installment_Amount { get; set; }
        public string Installment_Date { get; set; }
        public Nullable<short> State { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
    }
}
