//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purch_Refund_Invoice_MST
    {
        public int ID { get; set; }
        public long Serial { get; set; }
        public long Bill_Code { get; set; }
        public string BRN_Code { get; set; }
        public Nullable<int> ProcType { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<int> C_Date { get; set; }
        public Nullable<int> C_Time { get; set; }
        public string WorthDate { get; set; }
        public Nullable<int> Cash_Bnk_No { get; set; }
        public string Acc_Code { get; set; }
        public string Bnk_CheckNo { get; set; }
        public string Cur_Code { get; set; }
        public Nullable<float> Cur_Rate { get; set; }
        public string S_Code { get; set; }
        public string S_Acc_Code { get; set; }
        public Nullable<int> CostMethod { get; set; }
        public string Stor_Code { get; set; }
        public string CC_Code { get; set; }
        public string Proj_Code { get; set; }
        public Nullable<int> Refund_Type { get; set; }
        public string Refund_Type_Ref { get; set; }
        public string Ref { get; set; }
        public Nullable<float> Bill_Amount { get; set; }
        public Nullable<float> Bill_Discount { get; set; }
        public Nullable<float> Bill_Disc_Percent { get; set; }
        public Nullable<float> Bill_Discount_addational { get; set; }
        public Nullable<float> Bill_Expenses { get; set; }
        public Nullable<float> Bill_Burdens { get; set; }
        public Nullable<float> Bill_Taxs { get; set; }
        public Nullable<float> Bill_Total { get; set; }
        public Nullable<float> Bill_Total_After_Taxs { get; set; }
        public string description { get; set; }
        public Nullable<int> Item_Count { get; set; }
        public Nullable<bool> Use_Added_Value_Tax { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
        public Nullable<int> EditCount { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public Nullable<int> PiecesCount { get; set; }
    }
}
