//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Refund_Invoice_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_Refund_Invoice_MST()
        {
            this.Sales_Refund_Invoice_DTL = new HashSet<Sales_Refund_Invoice_DTL>();
        }
    
        public long ID { get; set; }
        public long Serial { get; set; }
        public long Bill_Code { get; set; }
        public int Brn_Code { get; set; }
        public int ProcType { get; set; }
        public Nullable<int> BillType { get; set; }
        public string InvoiceDate { get; set; }
        public int C_Date { get; set; }
        public Nullable<int> C_Time { get; set; }
        public Nullable<int> C_Code { get; set; }
        public string C_Nm { get; set; }
        public string C_Acc_Code { get; set; }
        public Nullable<int> Cash_Bnk_No { get; set; }
        public string Acc_Code { get; set; }
        public string Bnk_CheckNo { get; set; }
        public string Cur_Code { get; set; }
        public Nullable<float> Cur_Rate { get; set; }
        public Nullable<int> Stor_Code { get; set; }
        public float Stor_Cur_Rate { get; set; }
        public Nullable<int> CC_Code { get; set; }
        public Nullable<int> Proj_Code { get; set; }
        public Nullable<int> Refund_Type { get; set; }
        public string Refund_Type_Ref { get; set; }
        public string WorthDate { get; set; }
        public Nullable<bool> Use_Tax { get; set; }
        public Nullable<bool> isTaxIncludeBillPrice { get; set; }
        public Nullable<bool> isStor_Effect { get; set; }
        public string Description { get; set; }
        public string Ref { get; set; }
        public float Bill_Amount { get; set; }
        public float Bill_Itm_Disc { get; set; }
        public float Bill_Disc { get; set; }
        public float Bill_Disc_Percent { get; set; }
        public float Bill_Taxs { get; set; }
        public float Bill_Total { get; set; }
        public float CashMny { get; set; }
        public float VisaMny { get; set; }
        public Nullable<int> Visa_Code { get; set; }
        public Nullable<int> Visa_bnk_No { get; set; }
        public string Visa_Acc_Code { get; set; }
        public float VisaComm { get; set; }
        public Nullable<float> AllGivenMny { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
        public Nullable<short> ItemCount { get; set; }
        public Nullable<short> PiecesCount { get; set; }
        public Nullable<short> PrintCount { get; set; }
        public Nullable<short> EditCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Refund_Invoice_DTL> Sales_Refund_Invoice_DTL { get; set; }
    }
}
