//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_FiscalYears
    {
        public int PER_CODE { get; set; }
        public int PER_MONTHS { get; set; }
        public int STARTMONTH { get; set; }
        public int STARTYEAR { get; set; }
        public int ENDMONTH { get; set; }
        public int ENDYEAR { get; set; }
        public string NOTE { get; set; }
        public int STATE { get; set; }
        public string OPENDATE { get; set; }
        public string COLSEDATE { get; set; }
        public string ADUSER { get; set; }
    }
}
