//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Lists
    {
        public int ID { get; set; }
        public string ListID { get; set; }
        public string ListNm { get; set; }
        public string ListFrm { get; set; }
        public string ListType { get; set; }
    }
}
