//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ExecptionAchive
    {
        public long ID { get; set; }
        public string Frm_Name { get; set; }
        public string Sndr_Object { get; set; }
        public string ExMessage { get; set; }
        public string Machine_Code { get; set; }
        public string Machine_Nm { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
    }
}
