//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Trans_Types
    {
        public int ID { get; set; }
        public string Trans_Type_Code { get; set; }
        public string Trans_Type_NmAr { get; set; }
        public Nullable<int> StoringType { get; set; }
        public string StoringTypeNmAr { get; set; }
    }
}
