//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_FiscalMonths
    {
        public int ID { get; set; }
        public int PER_CODE { get; set; }
        public int MONTH_CODE { get; set; }
        public string NMAR { get; set; }
        public string NMEN { get; set; }
        public string FRISTDATE { get; set; }
        public string LASTDATE { get; set; }
        public int C_FRISTDATE { get; set; }
        public int C_LASTDATE { get; set; }
        public int YEAR { get; set; }
        public int STATE { get; set; }
        public string CLOSEDATE { get; set; }
        public Nullable<int> C_CLOSEDATE { get; set; }
        public string CLOSE_USR { get; set; }
    }
}
