//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ReportHeaderFoter2
    {
        public int ID { get; set; }
        public int Code { get; set; }
        public string User_id { get; set; }
        public string R1 { get; set; }
        public string R2 { get; set; }
        public string L1 { get; set; }
        public string L2 { get; set; }
        public string FoterLine { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<bool> isDef { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
