//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public long Bill_Code { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<float> TheTotal { get; set; }
        public Nullable<float> TheTotal_Refund { get; set; }
        public Nullable<float> TheTotal_Loc { get; set; }
        public string Symbol { get; set; }
    }
}
