//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Inv_OpenBalanceBrowse
    {
        public long Code { get; set; }
        public string Itm_Code { get; set; }
        public string NmAr { get; set; }
        public string Unt_NmAr { get; set; }
        public string Stor_NmAr { get; set; }
        public Nullable<int> Qnty { get; set; }
    }
}
