//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Inv_ItemsLov
    {
        public string Code { get; set; }
        public string NmAr { get; set; }
        public string NmEn { get; set; }
        public string MainGrp_NmAr { get; set; }
        public string ItmTyp_NmAr { get; set; }
        public string ItmCls_NmAr { get; set; }
        public string FavGrp_NmAr { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isNotForSal { get; set; }
    }
}
