//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Pur_Rep_Debt_Aging
    {
        public string BRN_NmAr { get; set; }
        public Nullable<long> Sub_Code { get; set; }
        public string NmAr { get; set; }
        public string Acc_Code { get; set; }
        public Nullable<long> Ref { get; set; }
        public string Cur_NmAr { get; set; }
        public string Symbol { get; set; }
        public Nullable<float> D_Amount { get; set; }
        public Nullable<float> C_Amount { get; set; }
        public string T_Desc { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<long> Serial { get; set; }
        public string CC_Code { get; set; }
        public string Proj_Code { get; set; }
        public Nullable<int> Mnth { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> BRN_No { get; set; }
        public string Cur_Code { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string WorthDate { get; set; }
        public Nullable<int> WorthType { get; set; }
        public string RecDate_G { get; set; }
        public Nullable<int> Collector_Code { get; set; }
        public Nullable<int> w_Code { get; set; }
        public string Stor_NmAr { get; set; }
        public string Proj_NmAr { get; set; }
        public string CC_NmAr { get; set; }
        public string Trans_Type_NmAr { get; set; }
        public Nullable<bool> isSub { get; set; }
        public Nullable<short> SubType { get; set; }
        public bool IsLocal { get; set; }
        public bool IsForeign { get; set; }
        public bool IsStoreCur { get; set; }
        public Nullable<float> FD_Amount { get; set; }
        public Nullable<float> FC_Amount { get; set; }
        public Nullable<float> Cur_Rate { get; set; }
        public Nullable<long> Proc_Code { get; set; }
        public string Proc_Date { get; set; }
        public Nullable<int> G_Code { get; set; }
        public Nullable<int> Type_Code { get; set; }
        public Nullable<int> Dgree_Code { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> SupplierCreditPeriod { get; set; }
        public Nullable<int> ProcType { get; set; }
    }
}
