//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_PurInvoiceEXP
    {
        public long Serial { get; set; }
        public long Bill_Code { get; set; }
        public string Expens_Acc { get; set; }
        public string Expens_Acc_NmAr { get; set; }
        public string Expens_Cur_NmAr { get; set; }
        public string Symbol { get; set; }
        public Nullable<float> Expens_Amount { get; set; }
        public Nullable<float> Expens_Amount_Bill { get; set; }
        public string Ctrl_Acc { get; set; }
        public string Expens_Cur_Code { get; set; }
        public Nullable<float> Expens_Cur_Rate { get; set; }
    }
}
