//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_Audit_Balance1
    {
        public int ID { get; set; }
        public string BRN_NmAr { get; set; }
        public string ParentCode { get; set; }
        public string Acc_Code { get; set; }
        public string NmAr { get; set; }
        public Nullable<int> Rec_Code { get; set; }
        public string ProcType_NmAr { get; set; }
        public Nullable<long> Ref { get; set; }
        public string Cur_NmAr { get; set; }
        public string Local_Cur { get; set; }
        public string Symbol { get; set; }
        public Nullable<float> D_Amount { get; set; }
        public Nullable<float> C_Amount { get; set; }
        public Nullable<float> FD_Amount { get; set; }
        public Nullable<float> FC_Amount { get; set; }
        public int D_Amount_Op { get; set; }
        public int C_Amount_Op { get; set; }
        public int FD_Amount_Op { get; set; }
        public int FC_Amount_Op { get; set; }
        public int D_Amount_Mov { get; set; }
        public int C_Amount_Mov { get; set; }
        public int FD_Amount_Mov { get; set; }
        public int FC_Amount_Mov { get; set; }
        public Nullable<float> D_Amount_C { get; set; }
        public Nullable<float> C_Amount_C { get; set; }
        public Nullable<float> FD_Amount_C { get; set; }
        public Nullable<float> FC_Amount_C { get; set; }
        public string T_Desc { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<long> Serial { get; set; }
        public string CC_Code { get; set; }
        public string Proj_Code { get; set; }
        public Nullable<int> Mnth { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> BRN_No { get; set; }
        public string Cur_Code { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string WorthDate { get; set; }
        public Nullable<int> WorthType { get; set; }
        public string RecDate_G { get; set; }
        public Nullable<int> Collector_Code { get; set; }
        public Nullable<int> w_Code { get; set; }
        public string Proj_NmAr { get; set; }
        public string CC_NmAr { get; set; }
        public Nullable<int> CC_Grp { get; set; }
        public string Trans_Type_NmAr { get; set; }
        public Nullable<bool> isSub { get; set; }
        public Nullable<short> SubType { get; set; }
        public Nullable<bool> IsLocal { get; set; }
        public Nullable<bool> IsForeign { get; set; }
        public Nullable<bool> IsStoreCur { get; set; }
        public Nullable<float> Cur_Rate { get; set; }
        public Nullable<int> ProcType { get; set; }
        public Nullable<int> Type_Code { get; set; }
        public Nullable<short> A_level { get; set; }
        public Nullable<int> A_Type { get; set; }
        public Nullable<int> A_MovType { get; set; }
        public Nullable<int> A_ReportType { get; set; }
        public Nullable<int> A_Group { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<bool> IsFav { get; set; }
        public Nullable<int> Sub_Code { get; set; }
    }
}
