//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_Inv_Storing1
    {
        public string Trns_Serial { get; set; }
        public string Itm_Code { get; set; }
        public string NmAr { get; set; }
        public string Stor_Code { get; set; }
        public Nullable<float> Stor_Qnty { get; set; }
        public Nullable<decimal> Stor_AVG_Cost { get; set; }
        public Nullable<float> Qnty_Math { get; set; }
        public string Trns_DT { get; set; }
        public string NmEn { get; set; }
        public string MainGrp_NmAr { get; set; }
        public string ItmTyp_NmAr { get; set; }
        public string FavGrp_NmAr { get; set; }
        public string ItmCls_NmAr { get; set; }
        public string BasUnt_NmAr { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isNotForSal { get; set; }
        public string MnGrp_Code { get; set; }
        public string ItmTyp_Code { get; set; }
        public string Cls_Code { get; set; }
        public string Itm_Prps { get; set; }
        public string FavGrp_Code { get; set; }
        public string BasUnt_Code { get; set; }
        public Nullable<bool> isSrvs_Itm { get; set; }
        public Nullable<bool> isReq_ExpireDT { get; set; }
        public Nullable<bool> isReq_Batch_Num { get; set; }
        public int isStored { get; set; }
        public string Stor_NmAr { get; set; }
        public Nullable<int> Brn_Code { get; set; }
        public Nullable<float> Qty_In { get; set; }
        public Nullable<float> Qty_out { get; set; }
        public string CC_Code { get; set; }
        public string Proj_Code { get; set; }
        public string Unt_Code { get; set; }
        public Nullable<float> Unt_Size { get; set; }
        public Nullable<float> Qnty_In { get; set; }
        public Nullable<float> Qnty_Out { get; set; }
        public Nullable<float> QtyFree_in { get; set; }
        public Nullable<float> QtyFree_out { get; set; }
        public Nullable<decimal> AVG_Cost { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public string Unt_NmAr { get; set; }
        public Nullable<int> BasUnt_Size { get; set; }
    }
}
