//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_Inv_Stor_Movment1
    {
        public int Trans_Type { get; set; }
        public Nullable<int> BRN_Code { get; set; }
        public Nullable<int> Stor_Code { get; set; }
        public string Itm_Code { get; set; }
        public string MnGrp_Code { get; set; }
        public string Unt_Code { get; set; }
        public Nullable<int> Qnty_Opn { get; set; }
        public Nullable<decimal> Total_Cost_Opn { get; set; }
        public float Qnty_In { get; set; }
        public Nullable<float> Total_Cost_In { get; set; }
        public float Qnty_Out { get; set; }
        public Nullable<float> Total_Cost_Out { get; set; }
        public int Qnty_Curr { get; set; }
        public int Total_Cost_Curr { get; set; }
        public Nullable<System.DateTime> AdDate { get; set; }
    }
}
