//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_Supplyer
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string NmAr { get; set; }
        public string NmEn { get; set; }
        public Nullable<int> G_Code { get; set; }
        public string S_Grp_NmAr { get; set; }
        public string S_Grp_NmEn { get; set; }
        public string Acc_Code { get; set; }
        public string SupplerType_NmAr { get; set; }
        public string SupplerDgree_NmAr { get; set; }
        public Nullable<bool> isTaxed { get; set; }
        public string Tax_Num { get; set; }
        public string Country_NmAr { get; set; }
        public string City_NmAr { get; set; }
        public string Area_NmAr { get; set; }
        public string adrs { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Note { get; set; }
        public string AdUser { get; set; }
        public Nullable<int> Type_Code { get; set; }
        public Nullable<int> Dgree_Code { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Area { get; set; }
        public string AdDate { get; set; }
    }
}
