//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_Inv_ItmPricing
    {
        public long Code { get; set; }
        public string Itm_Code { get; set; }
        public string NmAr { get; set; }
        public string Unt_NmAr { get; set; }
        public string Stor_NmAr { get; set; }
        public string Lvl_NmAr { get; set; }
        public Nullable<float> Cost_Price { get; set; }
        public Nullable<int> Cur_Code { get; set; }
        public string Cur_NmAr { get; set; }
        public string Symbol { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
        public string MainGrp_NmAr { get; set; }
        public string ItmTyp_NmAr { get; set; }
        public string FavGrp_NmAr { get; set; }
        public string ItmCls_NmAr { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isNotForSal { get; set; }
        public string MnGrp_Code { get; set; }
        public string ItmTyp_Code { get; set; }
        public string Cls_Code { get; set; }
        public string Itm_Prps { get; set; }
        public string FavGrp_Code { get; set; }
        public Nullable<int> Req_Lmt { get; set; }
        public Nullable<bool> isTaxed { get; set; }
        public Nullable<bool> isSrvs_Itm { get; set; }
        public Nullable<bool> isReq_ExpireDT { get; set; }
        public Nullable<bool> isReq_Batch_Num { get; set; }
        public Nullable<bool> haveDiscount_In_Purch { get; set; }
        public int isStored { get; set; }
        public Nullable<float> Tax_Percent { get; set; }
        public string Sply_Bil_No { get; set; }
        public Nullable<int> Brn_Code { get; set; }
        public string PricingLevel_Code { get; set; }
        public string Stor_Code { get; set; }
        public string Unt_Code { get; set; }
    }
}
