//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_RefundInvoiceDTL
    {
        public long Serial { get; set; }
        public long Bill_Code { get; set; }
        public string Itm_Code { get; set; }
        public string Itm_NmAr { get; set; }
        public string Unt_NmAr { get; set; }
        public string Batch_Num { get; set; }
        public string Stor_NmAr { get; set; }
        public float Qty { get; set; }
        public Nullable<float> Qty_Free { get; set; }
        public string ExpireDT { get; set; }
        public float Itm_Price { get; set; }
        public Nullable<float> Amount_inStor { get; set; }
        public Nullable<float> Total_Discount { get; set; }
        public Nullable<float> Expenses { get; set; }
        public Nullable<float> Tax_Value { get; set; }
        public Nullable<float> Itm_Total { get; set; }
        public string Note { get; set; }
        public float Qty_Total { get; set; }
        public Nullable<int> Rec_Seq { get; set; }
        public Nullable<int> Stor_Code { get; set; }
        public string Unt_Code { get; set; }
        public float Unt_Size { get; set; }
        public string MnGrp_NmAr { get; set; }
        public string MnGrp_Code { get; set; }
        public Nullable<float> TheTotal { get; set; }
        public Nullable<float> Discount_addational { get; set; }
        public string CC_Code { get; set; }
        public string CC_NmAr { get; set; }
        public string Proj_Code { get; set; }
        public string Proj_NmAr { get; set; }
        public string BRN_Code { get; set; }
        public Nullable<int> ProcType { get; set; }
        public string BRN_NmAr { get; set; }
        public string Cur_Code { get; set; }
        public Nullable<float> Cur_Rate { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<int> InvoiceMonth { get; set; }
        public Nullable<int> InvoiceYear { get; set; }
        public string WorthDate { get; set; }
        public string Ref { get; set; }
        public string Cur_NmAr { get; set; }
        public string Symbol { get; set; }
        public string Col_Code { get; set; }
        public string Col_Name { get; set; }
        public string S_Code { get; set; }
        public string S_NmAr { get; set; }
        public Nullable<float> Burdens { get; set; }
        public Nullable<float> Bill_Amount { get; set; }
        public Nullable<float> Bill_Discount { get; set; }
        public Nullable<float> Bill_Expenses { get; set; }
        public Nullable<float> Bill_Burdens { get; set; }
        public Nullable<float> Bill_Taxs { get; set; }
        public Nullable<float> Bill_Total { get; set; }
        public string description { get; set; }
        public string ItmTyp_Code { get; set; }
        public string Cls_Code { get; set; }
        public string FavGrp_Code { get; set; }
        public long Refund_Bill_Code { get; set; }
        public string ProcType_NmAr { get; set; }
        public Nullable<long> Refund_Bill_Serial { get; set; }
    }
}
