//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_SerialsWithProcCode
    {
        public long Proc_Serial { get; set; }
        public long Proc_Code { get; set; }
        public string Proc_Date { get; set; }
        public string Proc_DocType { get; set; }
    }
}
