//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_Inv_OpeningBalance
    {
        public long Code { get; set; }
        public string Itm_Code { get; set; }
        public string NmAr { get; set; }
        public string Unt_NmAr { get; set; }
        public string Stor_NmAr { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Itm_Price { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public string MainGrp_NmAr { get; set; }
        public string ItmTyp_NmAr { get; set; }
        public string FavGrp_NmAr { get; set; }
        public string ItmCls_NmAr { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MnGrp_Code { get; set; }
        public string ItmTyp_Code { get; set; }
        public string Cls_Code { get; set; }
        public string FavGrp_Code { get; set; }
        public string Unt_Code { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string Stor_Code { get; set; }
        public string Batch_Num { get; set; }
        public string ExpireDT { get; set; }
        public Nullable<int> Brn_Code { get; set; }
        public string Itm_Prps { get; set; }
        public string MainGrp_NmEn { get; set; }
    }
}
