//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_Sal_InvoiceDTL
    {
        public long Serial { get; set; }
        public long Bill_Code { get; set; }
        public string Itm_Code { get; set; }
        public string Itm_NmAr { get; set; }
        public string Unt_NmAr { get; set; }
        public string Batch_Num { get; set; }
        public string Stor_NmAr { get; set; }
        public float Qty { get; set; }
        public float Qty_free { get; set; }
        public string ExpireDT { get; set; }
        public float Itm_Price { get; set; }
        public float AVG_Cost { get; set; }
        public Nullable<float> Amount_inStor { get; set; }
        public float Prof_Value { get; set; }
        public Nullable<float> Total_Discount { get; set; }
        public float Tax_Value { get; set; }
        public Nullable<float> Itm_Total { get; set; }
        public string Note { get; set; }
        public float Qty_Total { get; set; }
        public Nullable<int> Rec_Seq { get; set; }
        public int Stor_Code { get; set; }
        public string Unt_Code { get; set; }
        public float Unt_Size { get; set; }
        public string MnGrp_NmAr { get; set; }
        public string MnGrp_Code { get; set; }
        public float TheTotal { get; set; }
        public Nullable<float> Discount_addational { get; set; }
        public Nullable<int> CC_Code { get; set; }
        public string CC_NmAr { get; set; }
        public Nullable<int> Proj_Code { get; set; }
        public string Proj_NmAr { get; set; }
        public int Brn_Code { get; set; }
        public int ProcType { get; set; }
        public string BRN_NmAr { get; set; }
        public Nullable<int> Cur_Code { get; set; }
        public Nullable<float> Cur_Rate { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<int> InvoiceMonth { get; set; }
        public Nullable<int> InvoiceYear { get; set; }
        public string WorthDate { get; set; }
        public string Ref { get; set; }
        public string Cur_NmAr { get; set; }
        public string Symbol { get; set; }
        public string Col_Code { get; set; }
        public string Col_Name { get; set; }
        public Nullable<int> C_Code { get; set; }
        public string C_NmAr { get; set; }
        public float Bill_Amount { get; set; }
        public float Bill_Disc { get; set; }
        public float Bill_Taxs { get; set; }
        public float Bill_Total { get; set; }
        public string Description { get; set; }
        public string ItmTyp_Code { get; set; }
        public string Cls_Code { get; set; }
        public string FavGrp_Code { get; set; }
        public string ProcType_NmAr { get; set; }
        public string FavGrp_NmAr { get; set; }
        public Nullable<int> BillType { get; set; }
        public string BillType_NmAr { get; set; }
        public long ID { get; set; }
        public string C_Nm { get; set; }
        public string C_Acc_Code { get; set; }
        public Nullable<int> Cash_Bnk_No { get; set; }
        public string Acc_Code { get; set; }
        public string Bnk_CheckNo { get; set; }
        public float Qty_Refunded { get; set; }
        public Nullable<float> Qty_Free_Refunded { get; set; }
        public Nullable<int> G_Code { get; set; }
        public Nullable<int> Type_Code { get; set; }
        public Nullable<int> Dgree_Code { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Area { get; set; }
    }
}
