//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_PurInvoiceMST
    {
        public int ID { get; set; }
        public string BRN_NmAr { get; set; }
        public long Serial { get; set; }
        public long Bill_Code { get; set; }
        public string ProcessType { get; set; }
        public string InvoiceDate { get; set; }
        public string Cash_Bank_S_NmAr { get; set; }
        public string WorthDate { get; set; }
        public string Cur_NmAr { get; set; }
        public Nullable<float> Bill_Amount { get; set; }
        public Nullable<float> Bill_Discount { get; set; }
        public Nullable<float> Bill_Total { get; set; }
        public string Ref { get; set; }
        public string Sply_Bil_No { get; set; }
        public Nullable<float> Bill_Expenses { get; set; }
        public Nullable<float> Bill_Burdens { get; set; }
        public Nullable<float> Bill_Taxs { get; set; }
        public Nullable<float> Bill_Total_After_Taxs { get; set; }
        public string description { get; set; }
        public string BRN_Code { get; set; }
        public Nullable<int> ProcType { get; set; }
        public Nullable<int> Cash_Bnk_No { get; set; }
        public string Acc_Code { get; set; }
        public string Cur_Code { get; set; }
        public string S_Code { get; set; }
        public string S_Acc_Code { get; set; }
        public string Symbol { get; set; }
        public Nullable<float> NetAmount { get; set; }
        public string Verify_Code { get; set; }
        public string CG_Acc { get; set; }
        public Nullable<float> Cur_Rate { get; set; }
        public string S_NmAr { get; set; }
        public string CC_Code { get; set; }
        public Nullable<float> Bill_Discount_addational { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string CC_NmAr { get; set; }
    }
}
