//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rep_Inv_TransferMST
    {
        public int ID { get; set; }
        public long Serial { get; set; }
        public long Bill_Code { get; set; }
        public string BRN_Code { get; set; }
        public Nullable<int> TransferType { get; set; }
        public string Process_Date { get; set; }
        public string Cur_Code { get; set; }
        public Nullable<float> Cur_Rate { get; set; }
        public string Stor_Code_From { get; set; }
        public string Stor_Code_To { get; set; }
        public Nullable<int> CostMethod { get; set; }
        public string PricingLevel_Code { get; set; }
        public string Reason { get; set; }
        public string CC_Code { get; set; }
        public string Proj_Code { get; set; }
        public string Broker_Acc_Code { get; set; }
        public string Burdens_Acc_Code { get; set; }
        public Nullable<float> Burdens_Amount { get; set; }
        public Nullable<float> Bill_Total { get; set; }
        public string Ref { get; set; }
        public string description { get; set; }
        public Nullable<bool> isUsed { get; set; }
        public Nullable<bool> isPending { get; set; }
        public Nullable<bool> isPosted { get; set; }
        public Nullable<bool> isReceived { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
        public Nullable<int> Item_Count { get; set; }
        public Nullable<int> EditCount { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public Nullable<int> PiecesCount { get; set; }
        public string BRN_NmAr { get; set; }
        public string TransferType_Nm { get; set; }
        public string Stor_Code_From_Nm { get; set; }
        public string Stor_Code_To_Nm { get; set; }
        public Nullable<long> Transfer_Code { get; set; }
        public string CC_NmAr { get; set; }
        public string Proj_NmAr { get; set; }
        public Nullable<int> Doc_Type { get; set; }
    }
}
