//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_VisaTypes
    {
        public int ID { get; set; }
        public int Code { get; set; }
        public string NmAr { get; set; }
        public string NmEn { get; set; }
        public Nullable<int> Bnk_No { get; set; }
        public string Bnk_Acc_Code { get; set; }
        public string Comm_Acc_Code { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<bool> HasComm { get; set; }
        public Nullable<bool> IsPayByCustomer { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
