//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acc_Accounts()
        {
            this.Acc_Transaction_DTL = new HashSet<Acc_Transaction_DTL>();
            this.Sales_Invoice_Mst = new HashSet<Sales_Invoice_Mst>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string ParentCode { get; set; }
        public string NmAr { get; set; }
        public string NmEn { get; set; }
        public Nullable<short> A_level { get; set; }
        public Nullable<int> A_Type { get; set; }
        public Nullable<int> A_MovType { get; set; }
        public Nullable<int> A_ReportType { get; set; }
        public Nullable<int> A_Group { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<bool> IsFav { get; set; }
        public Nullable<bool> isSub { get; set; }
        public Nullable<short> SubType { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
        public Nullable<int> BRN_Code { get; set; }
        public Nullable<int> Year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc_Transaction_DTL> Acc_Transaction_DTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Invoice_Mst> Sales_Invoice_Mst { get; set; }
    }
}
