//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Cash_InHand
    {
        public int ID { get; set; }
        public int CashNo { get; set; }
        public string NmAr { get; set; }
        public string NmEn { get; set; }
        public string Acc_Code { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<int> CashType { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<int> BRN_No { get; set; }
        public string Note { get; set; }
        public string adUser { get; set; }
        public string adDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
