//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_OpenBalance
    {
        public int ID { get; set; }
        public Nullable<long> Serial { get; set; }
        public string Acc_Code { get; set; }
        public Nullable<bool> isSub { get; set; }
        public Nullable<short> SubType { get; set; }
        public Nullable<int> Sub_Code { get; set; }
        public string Cur_Code { get; set; }
        public Nullable<float> Cur_RATE { get; set; }
        public Nullable<int> C_Code { get; set; }
        public Nullable<int> Cash_No { get; set; }
        public Nullable<int> Bnk_No { get; set; }
        public Nullable<int> Emp_Code { get; set; }
        public Nullable<int> S_Code { get; set; }
        public Nullable<float> D_Amount { get; set; }
        public Nullable<float> C_Amount { get; set; }
        public Nullable<float> FD_Amount { get; set; }
        public Nullable<float> FC_Amount { get; set; }
        public string Tagged { get; set; }
        public Nullable<int> CC_Code { get; set; }
        public Nullable<int> Proj_Code { get; set; }
        public Nullable<int> Verify_Code { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> BRN_No { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
    }
}
