//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Collectors
    {
        public int Collector_Code { get; set; }
        public string NmAr { get; set; }
        public string NmEn { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string adrs { get; set; }
        public Nullable<int> Area_Code { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
