//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_VisaTypes_Comm
    {
        public int id { get; set; }
        public int Visa_Code { get; set; }
        public Nullable<float> StartPrice { get; set; }
        public Nullable<float> EndPrice { get; set; }
        public Nullable<int> CommType { get; set; }
        public Nullable<float> CommAmount { get; set; }
    }
}
