//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Genral_Setting
    {
        public int ID { get; set; }
        public Nullable<bool> Use_Added_Value_Tax { get; set; }
        public Nullable<float> Tax_Percent { get; set; }
        public Nullable<int> TaxCalcMethod { get; set; }
        public Nullable<bool> TaxPercentFunc1 { get; set; }
        public Nullable<bool> TaxPercentFunc2 { get; set; }
        public Nullable<bool> Use_Batch_Num { get; set; }
        public Nullable<bool> Use_ExpireDT { get; set; }
        public Nullable<short> Digit_Num { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
