//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Inv_Setting
    {
        public int ID { get; set; }
        public Nullable<int> Indexing_ItemCode { get; set; }
        public Nullable<int> Indexing_Inv_Orders { get; set; }
        public Nullable<int> CCType_Inv_Orders { get; set; }
        public Nullable<bool> CC_Must_Inv_Orders { get; set; }
        public Nullable<int> ProjType_Inv_Orders { get; set; }
        public Nullable<bool> ProjMust_Inv_Orders { get; set; }
        public Nullable<bool> Dsply_Itm_Desc { get; set; }
        public Nullable<bool> Dsply_Itm_Notes { get; set; }
        public Nullable<short> Digit_Num { get; set; }
        public Nullable<bool> Multi_Stor { get; set; }
        public Nullable<bool> Use_Batch_Num { get; set; }
        public Nullable<bool> Use_ExpireDT { get; set; }
        public Nullable<bool> UpdateAutoItemCode { get; set; }
        public Nullable<int> ItemCode_Length { get; set; }
        public Nullable<short> Discounts_No { get; set; }
        public Nullable<int> ItemCost_Type { get; set; }
        public Nullable<int> ItemPricing_Type { get; set; }
        public Nullable<bool> Use_Added_Value_Tax { get; set; }
        public Nullable<float> Tax_Percent { get; set; }
        public Nullable<bool> is_SalPriceWithAddedTax { get; set; }
        public Nullable<int> LinkWithAccount { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
