//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Sales_Setting
    {
        public int ID { get; set; }
        public Nullable<int> Indexing_SaleInvoice { get; set; }
        public Nullable<int> CCType_SaleInvoice { get; set; }
        public Nullable<bool> CC_Must_SaleInvoice { get; set; }
        public Nullable<int> ProjType_SaleInvoice { get; set; }
        public Nullable<bool> ProjMust_SaleInvoice { get; set; }
        public Nullable<bool> UseMutliStore { get; set; }
        public Nullable<bool> UseBillDiscount { get; set; }
        public Nullable<bool> UseProductDiscount { get; set; }
        public Nullable<bool> UseDiscount1 { get; set; }
        public Nullable<bool> UseDiscount2 { get; set; }
        public Nullable<bool> UseDiscount3 { get; set; }
        public Nullable<bool> AutoFillDefualtPrice { get; set; }
        public Nullable<bool> UseFreeQty { get; set; }
        public Nullable<bool> UseProductDescription { get; set; }
        public Nullable<bool> EffectStore { get; set; }
        public Nullable<bool> AllowToChooseEffectedBills { get; set; }
        public Nullable<bool> AllowPriceLessThanCost { get; set; }
        public Nullable<bool> BillMasterFixed { get; set; }
    }
}
