//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccSys_JZ20171Entities : DbContext
    {
        public AccSys_JZ20171Entities()
            : base("name=AccSys_JZ20171Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Acc_Setting> C_Acc_Setting { get; set; }
        public virtual DbSet<C_Genral_Setting> C_Genral_Setting { get; set; }
        public virtual DbSet<C_Inv_Setting> C_Inv_Setting { get; set; }
        public virtual DbSet<C_Purch_Setting> C_Purch_Setting { get; set; }
        public virtual DbSet<C_Sales_Setting> C_Sales_Setting { get; set; }
        public virtual DbSet<Acc_AccountLinked> Acc_AccountLinked { get; set; }
        public virtual DbSet<Acc_Accounts> Acc_Accounts { get; set; }
        public virtual DbSet<Acc_Cash_AtBank> Acc_Cash_AtBank { get; set; }
        public virtual DbSet<Acc_Cash_InHand> Acc_Cash_InHand { get; set; }
        public virtual DbSet<Acc_CashBnk_Currency> Acc_CashBnk_Currency { get; set; }
        public virtual DbSet<Acc_Collectors> Acc_Collectors { get; set; }
        public virtual DbSet<Acc_CostCenter_Projects> Acc_CostCenter_Projects { get; set; }
        public virtual DbSet<Acc_Currency> Acc_Currency { get; set; }
        public virtual DbSet<Acc_OpenBalance> Acc_OpenBalance { get; set; }
        public virtual DbSet<Acc_Transaction_DTL> Acc_Transaction_DTL { get; set; }
        public virtual DbSet<Acc_Transaction_MST> Acc_Transaction_MST { get; set; }
        public virtual DbSet<Acc_VisaTypes> Acc_VisaTypes { get; set; }
        public virtual DbSet<Acc_VisaTypes_Comm> Acc_VisaTypes_Comm { get; set; }
        public virtual DbSet<Inv_AccountLinked> Inv_AccountLinked { get; set; }
        public virtual DbSet<Inv_AccountLinkeds> Inv_AccountLinkeds { get; set; }
        public virtual DbSet<Inv_Favorite_Groups> Inv_Favorite_Groups { get; set; }
        public virtual DbSet<Inv_Item_Barcode> Inv_Item_Barcode { get; set; }
        public virtual DbSet<Inv_Item_Types> Inv_Item_Types { get; set; }
        public virtual DbSet<Inv_Item_Units> Inv_Item_Units { get; set; }
        public virtual DbSet<Inv_Items> Inv_Items { get; set; }
        public virtual DbSet<Inv_Items_Classification> Inv_Items_Classification { get; set; }
        public virtual DbSet<Inv_Items_Pricing> Inv_Items_Pricing { get; set; }
        public virtual DbSet<Inv_Items_Suppliers> Inv_Items_Suppliers { get; set; }
        public virtual DbSet<Inv_Itm_Mov> Inv_Itm_Mov { get; set; }
        public virtual DbSet<Inv_Itm_Mov2> Inv_Itm_Mov2 { get; set; }
        public virtual DbSet<Inv_Main_Groups> Inv_Main_Groups { get; set; }
        public virtual DbSet<Inv_OpeningBalance> Inv_OpeningBalance { get; set; }
        public virtual DbSet<Inv_Pricing_Levels> Inv_Pricing_Levels { get; set; }
        public virtual DbSet<Inv_Receiving_DTL> Inv_Receiving_DTL { get; set; }
        public virtual DbSet<Inv_Receiving_MST> Inv_Receiving_MST { get; set; }
        public virtual DbSet<Inv_Store_Places> Inv_Store_Places { get; set; }
        public virtual DbSet<Inv_Stores> Inv_Stores { get; set; }
        public virtual DbSet<Inv_Storing> Inv_Storing { get; set; }
        public virtual DbSet<Inv_Trans_In_DTL> Inv_Trans_In_DTL { get; set; }
        public virtual DbSet<Inv_Trans_In_MST> Inv_Trans_In_MST { get; set; }
        public virtual DbSet<Inv_Trans_Out_DTL> Inv_Trans_Out_DTL { get; set; }
        public virtual DbSet<Inv_Trans_Out_MST> Inv_Trans_Out_MST { get; set; }
        public virtual DbSet<Inv_Transfer_DTL> Inv_Transfer_DTL { get; set; }
        public virtual DbSet<Inv_Transfer_MST> Inv_Transfer_MST { get; set; }
        public virtual DbSet<Inv_Transfer_Receiving_Types> Inv_Transfer_Receiving_Types { get; set; }
        public virtual DbSet<Inv_Trns_Types> Inv_Trns_Types { get; set; }
        public virtual DbSet<Inv_Units> Inv_Units { get; set; }
        public virtual DbSet<Purch_Burdens> Purch_Burdens { get; set; }
        public virtual DbSet<Purch_Invoice_Burdens> Purch_Invoice_Burdens { get; set; }
        public virtual DbSet<Purch_Invoice_DTL> Purch_Invoice_DTL { get; set; }
        public virtual DbSet<Purch_Invoice_Expenses> Purch_Invoice_Expenses { get; set; }
        public virtual DbSet<Purch_Invoice_Installment> Purch_Invoice_Installment { get; set; }
        public virtual DbSet<Purch_Invoice_MST> Purch_Invoice_MST { get; set; }
        public virtual DbSet<Purch_Refund_Invoice_DTL> Purch_Refund_Invoice_DTL { get; set; }
        public virtual DbSet<Purch_Refund_Invoice_MST> Purch_Refund_Invoice_MST { get; set; }
        public virtual DbSet<Purch_Suppler_Cur> Purch_Suppler_Cur { get; set; }
        public virtual DbSet<Purch_SupplerGroups> Purch_SupplerGroups { get; set; }
        public virtual DbSet<Purch_Supplers> Purch_Supplers { get; set; }
        public virtual DbSet<Sales_Customer_Cur> Sales_Customer_Cur { get; set; }
        public virtual DbSet<Sales_CustomerGroups> Sales_CustomerGroups { get; set; }
        public virtual DbSet<Sales_Customers> Sales_Customers { get; set; }
        public virtual DbSet<Sales_Invoice_DTL> Sales_Invoice_DTL { get; set; }
        public virtual DbSet<Sales_Invoice_Mst> Sales_Invoice_Mst { get; set; }
        public virtual DbSet<Sales_Refund_Invoice_DTL> Sales_Refund_Invoice_DTL { get; set; }
        public virtual DbSet<Sales_Refund_Invoice_MST> Sales_Refund_Invoice_MST { get; set; }
        public virtual DbSet<Sys_Areas> Sys_Areas { get; set; }
        public virtual DbSet<Sys_BRN> Sys_BRN { get; set; }
        public virtual DbSet<Sys_CMP> Sys_CMP { get; set; }
        public virtual DbSet<Sys_CodeList> Sys_CodeList { get; set; }
        public virtual DbSet<Sys_ExecptionAchive> Sys_ExecptionAchive { get; set; }
        public virtual DbSet<Sys_FiscalMonths> Sys_FiscalMonths { get; set; }
        public virtual DbSet<Sys_FiscalYears> Sys_FiscalYears { get; set; }
        public virtual DbSet<Sys_Lists> Sys_Lists { get; set; }
        public virtual DbSet<Sys_Machines> Sys_Machines { get; set; }
        public virtual DbSet<Sys_Perm_Definition> Sys_Perm_Definition { get; set; }
        public virtual DbSet<Sys_Rep_Tmplts> Sys_Rep_Tmplts { get; set; }
        public virtual DbSet<Sys_Rep_Types> Sys_Rep_Types { get; set; }
        public virtual DbSet<Sys_ReportHeaderFoter2> Sys_ReportHeaderFoter2 { get; set; }
        public virtual DbSet<sys_SystemTree> sys_SystemTree { get; set; }
        public virtual DbSet<Sys_Trans_Types> Sys_Trans_Types { get; set; }
        public virtual DbSet<Sys_UserLog> Sys_UserLog { get; set; }
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
        public virtual DbSet<Inv_Trans_In_DTL_Deleted> Inv_Trans_In_DTL_Deleted { get; set; }
        public virtual DbSet<Inv_Trans_Out_DTL_Deleted> Inv_Trans_Out_DTL_Deleted { get; set; }
        public virtual DbSet<Purch_Invoice_DTL_Deleted> Purch_Invoice_DTL_Deleted { get; set; }
        public virtual DbSet<Purch_Refund_Invoice_DTL_Deleted> Purch_Refund_Invoice_DTL_Deleted { get; set; }
    }
}
