//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_OpeningBalance
    {
        public decimal ID { get; set; }
        public long Code { get; set; }
        public Nullable<long> Serial { get; set; }
        public string Itm_Code { get; set; }
        public string Unt_Code { get; set; }
        public Nullable<int> Unt_Size { get; set; }
        public string Stor_Code { get; set; }
        public string Batch_Num { get; set; }
        public string ExpireDT { get; set; }
        public Nullable<decimal> Itm_Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
        public string MnGrp_Code { get; set; }
        public Nullable<int> Rec_Seq { get; set; }
        public string BRN_Code { get; set; }
    }
}
