//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Stores
    {
        public decimal ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> StrGrp_No { get; set; }
        public Nullable<int> Brn_Code { get; set; }
        public string NmAr { get; set; }
        public string NmEn { get; set; }
        public string Adrs { get; set; }
        public string Storkpr { get; set; }
        public string PhonNum { get; set; }
        public string Broker_Acc_Code { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isSal { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
