//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Items_Pricing
    {
        public long ID { get; set; }
        public long Code { get; set; }
        public string Itm_Code { get; set; }
        public string Stor_Code { get; set; }
        public string Unt_Code { get; set; }
        public string PricingLevel_Code { get; set; }
        public Nullable<float> Cost_Price { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
