//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Perm_Definition
    {
        public long ID { get; set; }
        public string User_ID { get; set; }
        public string ListID { get; set; }
        public string Code { get; set; }
        public string SubCode { get; set; }
        public bool IsAdd { get; set; }
        public bool IsView { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
    }
}
