//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Rep_Tmplts
    {
        public int Code { get; set; }
        public Nullable<int> Type_id { get; set; }
        public string Rep_ID { get; set; }
        public Nullable<int> Rep_index { get; set; }
        public string NmAr { get; set; }
        public string NmEn { get; set; }
        public string Rep_Name { get; set; }
        public Nullable<bool> isUsed { get; set; }
    }
}
