//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONEX_Seles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_CodeList
    {
        public int ID { get; set; }
        public int Item_Code { get; set; }
        public string Item_NmAr { get; set; }
        public string Item_NmEn { get; set; }
        public string ListID { get; set; }
        public Nullable<int> Parent_Code { get; set; }
        public string Note { get; set; }
        public string AdUser { get; set; }
        public string AdDate { get; set; }
        public string EditUser { get; set; }
        public string EditDate { get; set; }
    }
}
